/*
 * Copyright (C) 2016-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.pustike.persist.metadata;

/**
 * The column type enumeration.
 */
public enum ColumnType {
    /**
     * The @{@link io.github.pustike.persist.Id} annotated field of type {@link Short} or {@link Integer} or {@link Long}
     * and which are respectively mapped to {@code smallint}, {@code integer}, {@code bigint}.
     * And additionally this column is defined as: {@code NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY}
     */
    Id,

    /**
     * All fields which are @{@link io.github.pustike.persist.Column} annotated or not annotated and
     * not {@code transient}. Following types are supported: <br>
     * {@link Boolean} - {@code boolean} <br>
     * {@link Byte} - {@code tinyint} <br>
     * {@link Character} - {@code char} <br>
     * {@link String} - {@code varchar} <br>
     * {@link Short} - {@code smallint} <br>
     * {@link Integer} - {@code integer} <br>
     * {@link Long} - {@code bigint} <br>
     * {@link Float} - {@code numeric} <br>
     * {@link Double} - {@code numeric} <br>
     * {@link java.math.BigInteger} - {@code numeric} <br>
     * {@link java.math.BigDecimal} - {@code numeric} <br>
     * {@link java.time.LocalDate} - {@code date} <br>
     * {@link java.time.LocalTime} - {@code time} <br>
     * {@link java.time.LocalDateTime} - {@code timestamp}
     */
    Default,

    /**
     * {@link Enum} type of fields mapped to {@code varchar} columns.
     */
    Enum,

    /**
     * {@link String} or {@link Byte}[] type of fields mapped to {@code text} or {@code bytea} column types.
     */
    Lob,

    /**
     * Fields of other entity type created with a foreign key constraint and as {@code bigint}
     */
    ForeignKey,

    /**
     * The @{@link io.github.pustike.persist.Version} annotated field of type {@link Short} or {@link Integer}
     * or {@link Long} and which are respectively mapped to {@code smallint}, {@code integer}, {@code bigint}.
     */
    Version,
}
